### ISSUE TITLE
Error on install Craft with pip in linux(wsl)

### ISSUE THREAD

**Issue by mahdibigdely** [fcakyon/craft-text-detector#43]
hi 
I  need to use craft-text-detector on ubuntu wsl to detect texts 
but in install via this pip command
`pip install craft-text-detector`

give me these outputs

Collecting craft-text-detector
  Using cached craft_text_detector-0.4.0-py3-none-any.whl (18 kB)
Processing /home/mahdi/.cache/pip/wheels/2b/3c/51/52c46deda5cd1d59c6ce3d441ea5f3d155495dc294c4535a25/gdown-4.2.0-py3-none-any.whl
Collecting opencv-python>=3.4.8.29
  Using cached opencv_python-4.5.4.60-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (60.3 MB)
Collecting torch>=1.6.0
  Using cached torch-1.10.0-cp38-cp38-manylinux1_x86_64.whl (881.9 MB)
ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/tmp/pip-install-y4okbzq2/torch/torch/lib/libtorch_cpu.so'

ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 476, in run
  File "/usr/lib/python3/dist-packages/pip/_internal/cache.py", line 329, in cleanup
  File "/usr/lib/python3/dist-packages/pip/_internal/cache.py", line 275, in cleanup
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/temp_dir.py", line 175, in cleanup
  File "/usr/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/share/python-wheels/six-1.14.0-py2.py3-none-any.whl/six.py", line 703, in reraise
    raise value
  File "/usr/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/misc.py", line 135, in rmtree
  File "/usr/lib/python3.8/shutil.py", line 722, in rmtree
  File "/usr/lib/python3.8/shutil.py", line 720, in rmtree
OSError: [Errno 30] Read-only file system: '/tmp/pip-ephem-wheel-cache-0z8k6dc7'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
  File "/usr/lib/python3/dist-packages/pip/_internal/req/req_tracker.py", line 42, in update_env_context_manager
  File "/usr/lib/python3/dist-packages/pip/_internal/req/req_tracker.py", line 66, in get_requirement_tracker
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 476, in run
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/temp_dir.py", line 153, in __exit__
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/temp_dir.py", line 175, in cleanup
  File "/usr/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/share/python-wheels/six-1.14.0-py2.py3-none-any.whl/six.py", line 703, in reraise
    raise value
  File "/usr/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/misc.py", line 135, in rmtree
  File "/usr/lib/python3.8/shutil.py", line 718, in rmtree
  File "/usr/lib/python3.8/shutil.py", line 655, in _rmtree_safe_fd
  File "/usr/lib/python3.8/shutil.py", line 655, in _rmtree_safe_fd
  File "/usr/lib/python3.8/shutil.py", line 675, in _rmtree_safe_fd
  File "/usr/lib/python3.8/shutil.py", line 673, in _rmtree_safe_fd
OSError: [Errno 30] Read-only file system: 'parse_url.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 186, in _main
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 476, in run
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
  File "/usr/lib/python3/dist-packages/pip/_internal/req/req_tracker.py", line 66, in get_requirement_tracker
  File "/usr/share/python-wheels/contextlib2-0.6.0-py2.py3-none-any.whl/contextlib2.py", line 479, in __exit__
    _reraise_with_existing_context(exc_details)
  File "/usr/share/python-wheels/contextlib2-0.6.0-py2.py3-none-any.whl/contextlib2.py", line 340, in _reraise_with_existing_context
    raise exc_details[1]
  File "/usr/share/python-wheels/contextlib2-0.6.0-py2.py3-none-any.whl/contextlib2.py", line 468, in __exit__
    if cb(*exc_details):
  File "/usr/share/python-wheels/contextlib2-0.6.0-py2.py3-none-any.whl/contextlib2.py", line 396, in _exit_wrapper
    return cm_exit(cm, *exc_details)
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/temp_dir.py", line 153, in __exit__
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/temp_dir.py", line 175, in cleanup
  File "/usr/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/share/python-wheels/six-1.14.0-py2.py3-none-any.whl/six.py", line 703, in reraise
    raise value
  File "/usr/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/misc.py", line 135, in rmtree
  File "/usr/lib/python3.8/shutil.py", line 722, in rmtree
  File "/usr/lib/python3.8/shutil.py", line 720, in rmtree
OSError: [Errno 30] Read-only file system: '/tmp/pip-req-tracker-zjjvy5zu'
Traceback (most recent call last):
  File "/usr/share/python-wheels/contextlib2-0.6.0-py2.py3-none-any.whl/contextlib2.py", line 468, in __exit__
  File "/usr/share/python-wheels/contextlib2-0.6.0-py2.py3-none-any.whl/contextlib2.py", line 396, in _exit_wrapper
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/temp_dir.py", line 153, in __exit__
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/temp_dir.py", line 175, in cleanup
  File "/usr/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl/retrying.py", line 49, in wrapped_f
  File "/usr/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl/retrying.py", line 212, in call
  File "/usr/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl/retrying.py", line 247, in get
  File "/usr/share/python-wheels/six-1.14.0-py2.py3-none-any.whl/six.py", line 703, in reraise
  File "/usr/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl/retrying.py", line 200, in call
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/misc.py", line 135, in rmtree
  File "/usr/lib/python3.8/shutil.py", line 718, in rmtree
  File "/usr/lib/python3.8/shutil.py", line 675, in _rmtree_safe_fd
  File "/usr/lib/python3.8/shutil.py", line 673, in _rmtree_safe_fd
OSError: [Errno 30] Read-only file system: 'torch-1.10.0-cp38-cp38-manylinux1_x86_64.whl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/python-wheels/contextlib2-0.6.0-py2.py3-none-any.whl/contextlib2.py", line 468, in __exit__
  File "/usr/share/python-wheels/contextlib2-0.6.0-py2.py3-none-any.whl/contextlib2.py", line 396, in _exit_wrapper
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/temp_dir.py", line 153, in __exit__
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/temp_dir.py", line 175, in cleanup
  File "/usr/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl/retrying.py", line 49, in wrapped_f
  File "/usr/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl/retrying.py", line 212, in call
  File "/usr/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl/retrying.py", line 247, in get
  File "/usr/share/python-wheels/six-1.14.0-py2.py3-none-any.whl/six.py", line 703, in reraise
  File "/usr/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl/retrying.py", line 200, in call
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/misc.py", line 135, in rmtree
  File "/usr/lib/python3.8/shutil.py", line 718, in rmtree
  File "/usr/lib/python3.8/shutil.py", line 675, in _rmtree_safe_fd
  File "/usr/lib/python3.8/shutil.py", line 673, in _rmtree_safe_fd
OSError: [Errno 30] Read-only file system: 'opencv_python-4.5.4.60-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pip", line 11, in <module>
    load_entry_point('pip==20.0.2', 'console_scripts', 'pip')()
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 75, in main
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 105, in main
  File "/usr/lib/python3.8/contextlib.py", line 120, in __exit__
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/command_context.py", line 28, in main_context
  File "/usr/share/python-wheels/contextlib2-0.6.0-py2.py3-none-any.whl/contextlib2.py", line 479, in __exit__
  File "/usr/share/python-wheels/contextlib2-0.6.0-py2.py3-none-any.whl/contextlib2.py", line 340, in _reraise_with_existing_context
  File "/usr/share/python-wheels/contextlib2-0.6.0-py2.py3-none-any.whl/contextlib2.py", line 468, in __exit__
  File "/usr/share/python-wheels/contextlib2-0.6.0-py2.py3-none-any.whl/contextlib2.py", line 396, in _exit_wrapper
  File "/usr/lib/python3.8/contextlib.py", line 120, in __exit__
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/temp_dir.py", line 36, in global_tempdir_manager
  File "/usr/share/python-wheels/contextlib2-0.6.0-py2.py3-none-any.whl/contextlib2.py", line 479, in __exit__
  File "/usr/share/python-wheels/contextlib2-0.6.0-py2.py3-none-any.whl/contextlib2.py", line 340, in _reraise_with_existing_context
  File "/usr/share/python-wheels/contextlib2-0.6.0-py2.py3-none-any.whl/contextlib2.py", line 468, in __exit__
  File "/usr/share/python-wheels/contextlib2-0.6.0-py2.py3-none-any.whl/contextlib2.py", line 396, in _exit_wrapper
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/temp_dir.py", line 153, in __exit__
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/temp_dir.py", line 175, in cleanup
  File "/usr/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl/retrying.py", line 49, in wrapped_f
  File "/usr/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl/retrying.py", line 212, in call
  File "/usr/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl/retrying.py", line 247, in get
  File "/usr/share/python-wheels/six-1.14.0-py2.py3-none-any.whl/six.py", line 703, in reraise
  File "/usr/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl/retrying.py", line 200, in call
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/misc.py", line 135, in rmtree
  File "/usr/lib/python3.8/shutil.py", line 718, in rmtree
  File "/usr/lib/python3.8/shutil.py", line 675, in _rmtree_safe_fd
  File "/usr/lib/python3.8/shutil.py", line 673, in _rmtree_safe_fd
OSError: [Errno 30] Read-only file system: 'craft_text_detector-0.4.0-py3-none-any.whl'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
OSError: [Errno 5] Input/output error: '/var/crash/_usr_bin_pip.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/share/python-wheels/contextlib2-0.6.0-py2.py3-none-any.whl/contextlib2.py", line 468, in __exit__
  File "/usr/share/python-wheels/contextlib2-0.6.0-py2.py3-none-any.whl/contextlib2.py", line 396, in _exit_wrapper
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/temp_dir.py", line 153, in __exit__
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/temp_dir.py", line 175, in cleanup
  File "/usr/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl/retrying.py", line 49, in wrapped_f
  File "/usr/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl/retrying.py", line 212, in call
  File "/usr/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl/retrying.py", line 247, in get
  File "/usr/share/python-wheels/six-1.14.0-py2.py3-none-any.whl/six.py", line 703, in reraise
  File "/usr/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl/retrying.py", line 200, in call
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/misc.py", line 135, in rmtree
  File "/usr/lib/python3.8/shutil.py", line 718, in rmtree
  File "/usr/lib/python3.8/shutil.py", line 675, in _rmtree_safe_fd
  File "/usr/lib/python3.8/shutil.py", line 673, in _rmtree_safe_fd
OSError: [Errno 30] Read-only file system: 'torch-1.10.0-cp38-cp38-manylinux1_x86_64.whl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/python-wheels/contextlib2-0.6.0-py2.py3-none-any.whl/contextlib2.py", line 468, in __exit__
  File "/usr/share/python-wheels/contextlib2-0.6.0-py2.py3-none-any.whl/contextlib2.py", line 396, in _exit_wrapper
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/temp_dir.py", line 153, in __exit__
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/temp_dir.py", line 175, in cleanup
  File "/usr/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl/retrying.py", line 49, in wrapped_f
  File "/usr/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl/retrying.py", line 212, in call
  File "/usr/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl/retrying.py", line 247, in get
  File "/usr/share/python-wheels/six-1.14.0-py2.py3-none-any.whl/six.py", line 703, in reraise
  File "/usr/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl/retrying.py", line 200, in call
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/misc.py", line 135, in rmtree
  File "/usr/lib/python3.8/shutil.py", line 718, in rmtree
  File "/usr/lib/python3.8/shutil.py", line 675, in _rmtree_safe_fd
  File "/usr/lib/python3.8/shutil.py", line 673, in _rmtree_safe_fd
OSError: [Errno 30] Read-only file system: 'opencv_python-4.5.4.60-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pip", line 11, in <module>
    load_entry_point('pip==20.0.2', 'console_scripts', 'pip')()
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 75, in main
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 105, in main
  File "/usr/lib/python3.8/contextlib.py", line 120, in __exit__
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/command_context.py", line 28, in main_context
  File "/usr/share/python-wheels/contextlib2-0.6.0-py2.py3-none-any.whl/contextlib2.py", line 479, in __exit__
  File "/usr/share/python-wheels/contextlib2-0.6.0-py2.py3-none-any.whl/contextlib2.py", line 340, in _reraise_with_existing_context
  File "/usr/share/python-wheels/contextlib2-0.6.0-py2.py3-none-any.whl/contextlib2.py", line 468, in __exit__
  File "/usr/share/python-wheels/contextlib2-0.6.0-py2.py3-none-any.whl/contextlib2.py", line 396, in _exit_wrapper
  File "/usr/lib/python3.8/contextlib.py", line 120, in __exit__
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/temp_dir.py", line 36, in global_tempdir_manager
  File "/usr/share/python-wheels/contextlib2-0.6.0-py2.py3-none-any.whl/contextlib2.py", line 479, in __exit__
  File "/usr/share/python-wheels/contextlib2-0.6.0-py2.py3-none-any.whl/contextlib2.py", line 340, in _reraise_with_existing_context
  File "/usr/share/python-wheels/contextlib2-0.6.0-py2.py3-none-any.whl/contextlib2.py", line 468, in __exit__
  File "/usr/share/python-wheels/contextlib2-0.6.0-py2.py3-none-any.whl/contextlib2.py", line 396, in _exit_wrapper
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/temp_dir.py", line 153, in __exit__
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/temp_dir.py", line 175, in cleanup
  File "/usr/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl/retrying.py", line 49, in wrapped_f
  File "/usr/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl/retrying.py", line 212, in call
  File "/usr/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl/retrying.py", line 247, in get
  File "/usr/share/python-wheels/six-1.14.0-py2.py3-none-any.whl/six.py", line 703, in reraise
  File "/usr/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl/retrying.py", line 200, in call
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/misc.py", line 135, in rmtree
  File "/usr/lib/python3.8/shutil.py", line 718, in rmtree
  File "/usr/lib/python3.8/shutil.py", line 675, in _rmtree_safe_fd
  File "/usr/lib/python3.8/shutil.py", line 673, in _rmtree_safe_fd
OSError: [Errno 30] Read-only file system: 'craft_text_detector-0.4.0-py3-none-any.whl'

**Comment by fcakyon** [comment]
This issue is not related to `craft-text-detector` but related with your computer.

Please check this solutions:
- https://askubuntu.com/questions/712860/how-to-solve-errno-30-read-only-file-system
- https://stackoverflow.com/questions/60042534/pipenv-oserror-errno-30-read-only-file-system
- https://stackoverflow.com/questions/63085356/oserror-errno-30-read-only-file-system-user-macos-catalina
- https://github.com/pypa/virtualenv/issues/209
- https://www.kaggle.com/questions-and-answers/70138
-
